[2025-03-15T18:20:07.775+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-15T18:20:07.799+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.first_task manual__2025-03-15T18:20:02.677832+00:00 [queued]>
[2025-03-15T18:20:07.811+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.first_task manual__2025-03-15T18:20:02.677832+00:00 [queued]>
[2025-03-15T18:20:07.812+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-15T18:20:07.830+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): first_task> on 2025-03-15 18:20:02.677832+00:00
[2025-03-15T18:20:07.838+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=101) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-15T18:20:07.840+0000] {standard_task_runner.py:72} INFO - Started process 102 to run task
[2025-03-15T18:20:07.840+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'solar_energy_crops_pipeline', 'first_task', 'manual__2025-03-15T18:20:02.677832+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/mainDag.py', '--cfg-path', '/tmp/tmp2ehc2pkp']
[2025-03-15T18:20:07.841+0000] {standard_task_runner.py:105} INFO - Job 113: Subtask first_task
[2025-03-15T18:20:07.955+0000] {task_command.py:467} INFO - Running <TaskInstance: solar_energy_crops_pipeline.first_task manual__2025-03-15T18:20:02.677832+00:00 [running]> on host 26a73488cd9b
[2025-03-15T18:20:08.110+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_energy_crops_pipeline' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T18:20:02.677832+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-15T18:20:02.677832+00:00'
[2025-03-15T18:20:08.111+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-15T18:20:08.154+0000] {base.py:84} INFO - Retrieving connection 'spark_mm'
[2025-03-15T18:20:08.157+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark jobs/Script1.py
[2025-03-15T18:20:14.042+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO SparkContext: Running Spark version 3.5.5
[2025-03-15T18:20:14.047+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-03-15T18:20:14.048+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO SparkContext: Java version 17.0.14
[2025-03-15T18:20:14.184+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-15T18:20:14.389+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO ResourceUtils: ==============================================================
[2025-03-15T18:20:14.390+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-15T18:20:14.391+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO ResourceUtils: ==============================================================
[2025-03-15T18:20:14.392+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO SparkContext: Submitted application: PythonWordCount
[2025-03-15T18:20:14.490+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-15T18:20:14.500+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO ResourceProfile: Limiting resource is cpu
[2025-03-15T18:20:14.501+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-15T18:20:14.613+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO SecurityManager: Changing view acls to: ***
[2025-03-15T18:20:14.615+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO SecurityManager: Changing modify acls to: ***
[2025-03-15T18:20:14.616+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO SecurityManager: Changing view acls groups to:
[2025-03-15T18:20:14.616+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO SecurityManager: Changing modify acls groups to:
[2025-03-15T18:20:14.617+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:14 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-03-15T18:20:15.189+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:15 INFO Utils: Successfully started service 'sparkDriver' on port 42595.
[2025-03-15T18:20:15.306+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:15 INFO SparkEnv: Registering MapOutputTracker
[2025-03-15T18:20:15.478+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:15 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-15T18:20:15.514+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:15 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-15T18:20:15.515+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:15 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-15T18:20:15.520+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:15 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-15T18:20:15.583+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:15 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-169387cc-ab61-4c8a-8413-0f003f0c588d
[2025-03-15T18:20:15.605+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:15 INFO MemoryStore: MemoryStore started with capacity 413.9 MiB
[2025-03-15T18:20:15.623+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:15 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-15T18:20:15.880+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:15 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-15T18:20:15.989+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:15 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-15T18:20:16.379+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:16 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-03-15T18:20:16.488+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:16 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.4:7077 after 77 ms (0 ms spent in bootstraps)
[2025-03-15T18:20:17.324+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:17 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250315182017-0000
[2025-03-15T18:20:17.339+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:17 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36463.
[2025-03-15T18:20:17.340+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:17 INFO NettyBlockTransferService: Server created on 26a73488cd9b:36463
[2025-03-15T18:20:17.342+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:17 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-15T18:20:17.358+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:17 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 26a73488cd9b, 36463, None)
[2025-03-15T18:20:17.365+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:17 INFO BlockManagerMasterEndpoint: Registering block manager 26a73488cd9b:36463 with 413.9 MiB RAM, BlockManagerId(driver, 26a73488cd9b, 36463, None)
[2025-03-15T18:20:17.369+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:17 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 26a73488cd9b, 36463, None)
[2025-03-15T18:20:17.372+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:17 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 26a73488cd9b, 36463, None)
[2025-03-15T18:20:17.411+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:17 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250315182017-0000/0 on worker-20250315181643-172.18.0.6-39107 (172.18.0.6:39107) with 2 core(s)
[2025-03-15T18:20:17.414+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:17 INFO StandaloneSchedulerBackend: Granted executor ID app-20250315182017-0000/0 on hostPort 172.18.0.6:39107 with 2 core(s), 1024.0 MiB RAM
[2025-03-15T18:20:18.314+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:18 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-15T18:20:20.679+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:20 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250315182017-0000/0 is now RUNNING
[2025-03-15T18:20:21.379+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:21 INFO SparkContext: Starting job: collect at /opt/***/jobs/Script1.py:21
[2025-03-15T18:20:21.475+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:21 INFO DAGScheduler: Registering RDD 2 (reduceByKey at /opt/***/jobs/Script1.py:19) as input to shuffle 0
[2025-03-15T18:20:21.483+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:21 INFO DAGScheduler: Got job 0 (collect at /opt/***/jobs/Script1.py:21) with 2 output partitions
[2025-03-15T18:20:21.484+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:21 INFO DAGScheduler: Final stage: ResultStage 1 (collect at /opt/***/jobs/Script1.py:21)
[2025-03-15T18:20:21.485+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:21 INFO DAGScheduler: Parents of final stage: List(ShuffleMapStage 0)
[2025-03-15T18:20:21.486+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:21 INFO DAGScheduler: Missing parents: List(ShuffleMapStage 0)
[2025-03-15T18:20:21.493+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:21 INFO DAGScheduler: Submitting ShuffleMapStage 0 (PairwiseRDD[2] at reduceByKey at /opt/***/jobs/Script1.py:19), which has no missing parents
[2025-03-15T18:20:21.814+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:21 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 10.9 KiB, free 413.9 MiB)
[2025-03-15T18:20:22.018+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:22 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 7.0 KiB, free 413.9 MiB)
[2025-03-15T18:20:22.076+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:22 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 26a73488cd9b:36463 (size: 7.0 KiB, free: 413.9 MiB)
[2025-03-15T18:20:22.085+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:22 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1585
[2025-03-15T18:20:22.117+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:22 INFO DAGScheduler: Submitting 2 missing tasks from ShuffleMapStage 0 (PairwiseRDD[2] at reduceByKey at /opt/***/jobs/Script1.py:19) (first 15 tasks are for partitions Vector(0, 1))
[2025-03-15T18:20:22.120+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:22 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks resource profile 0
[2025-03-15T18:20:30.335+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:30 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@2ecce683)) by listener AppStatusListener took 1.150793225s.
[2025-03-15T18:20:39.550+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:39 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-15T18:20:52.743+0000] {spark_submit.py:488} INFO - 25/03/15 18:20:52 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-15T18:20:58.688+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-03-15T18:21:01.285+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-15T18:21:04.306+0000] {spark_submit.py:488} INFO - 25/03/15 18:21:04 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@255cbcf4)) by listener AppStatusListener took 1.738040851s.
[2025-03-15T18:21:07.632+0000] {spark_submit.py:488} INFO - 25/03/15 18:21:07 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-15T18:21:22.224+0000] {spark_submit.py:488} INFO - 25/03/15 18:21:22 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-15T18:21:37.211+0000] {spark_submit.py:488} INFO - 25/03/15 18:21:37 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-15T18:21:39.118+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-15T18:21:49.583+0000] {spark_submit.py:488} INFO - 25/03/15 18:21:49 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@2a88921e)) by listener AppStatusListener took 2.246935948s.
[2025-03-15T18:21:52.778+0000] {spark_submit.py:488} INFO - 25/03/15 18:21:52 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-15T18:22:07.808+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:07 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-15T18:22:19.283+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-15T18:22:22.186+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:22 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-15T18:22:25.531+0000] {job.py:229} INFO - Heartbeat recovered after 127.35 seconds
[2025-03-15T18:22:26.046+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:26 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.6:47064) with ID 0,  ResourceProfileId 0
[2025-03-15T18:22:26.477+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:26 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.6:46841 with 434.4 MiB RAM, BlockManagerId(0, 172.18.0.6, 46841, None)
[2025-03-15T18:22:26.859+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:26 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.18.0.6, executor 0, partition 0, PROCESS_LOCAL, 9212 bytes)
[2025-03-15T18:22:26.945+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:26 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1) (172.18.0.6, executor 0, partition 1, PROCESS_LOCAL, 9219 bytes)
[2025-03-15T18:22:27.852+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:27 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.18.0.6:46841 (size: 7.0 KiB, free: 434.4 MiB)
[2025-03-15T18:22:31.966+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:31 INFO TaskSetManager: Finished task 1.0 in stage 0.0 (TID 1) in 5093 ms on 172.18.0.6 (executor 0) (1/2)
[2025-03-15T18:22:32.087+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:31 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 5192 ms on 172.18.0.6 (executor 0) (2/2)
[2025-03-15T18:22:32.097+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2025-03-15T18:22:32.192+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO PythonAccumulatorV2: Connected to AccumulatorServer at host: 127.0.0.1 port: 47243
[2025-03-15T18:22:32.249+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO DAGScheduler: ShuffleMapStage 0 (reduceByKey at /opt/***/jobs/Script1.py:19) finished in 130.669 s
[2025-03-15T18:22:32.252+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO DAGScheduler: looking for newly runnable stages
[2025-03-15T18:22:32.253+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO DAGScheduler: running: Set()
[2025-03-15T18:22:32.254+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO DAGScheduler: waiting: Set(ResultStage 1)
[2025-03-15T18:22:32.255+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO DAGScheduler: failed: Set()
[2025-03-15T18:22:32.261+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO DAGScheduler: Submitting ResultStage 1 (PythonRDD[5] at collect at /opt/***/jobs/Script1.py:21), which has no missing parents
[2025-03-15T18:22:32.449+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 10.0 KiB, free 413.9 MiB)
[2025-03-15T18:22:32.462+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 6.0 KiB, free 413.9 MiB)
[2025-03-15T18:22:32.464+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 26a73488cd9b:36463 (size: 6.0 KiB, free: 413.9 MiB)
[2025-03-15T18:22:32.467+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1585
[2025-03-15T18:22:32.470+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO DAGScheduler: Submitting 2 missing tasks from ResultStage 1 (PythonRDD[5] at collect at /opt/***/jobs/Script1.py:21) (first 15 tasks are for partitions Vector(0, 1))
[2025-03-15T18:22:33.000+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:32 INFO TaskSchedulerImpl: Adding task set 1.0 with 2 tasks resource profile 0
[2025-03-15T18:22:34.471+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:34 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 2) (172.18.0.6, executor 0, partition 0, NODE_LOCAL, 8821 bytes)
[2025-03-15T18:22:34.489+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:34 INFO TaskSetManager: Starting task 1.0 in stage 1.0 (TID 3) (172.18.0.6, executor 0, partition 1, NODE_LOCAL, 8821 bytes)
[2025-03-15T18:22:35.041+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:35 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 172.18.0.6:46841 (size: 6.0 KiB, free: 434.4 MiB)
[2025-03-15T18:22:53.345+0000] {spark_submit.py:488} INFO - 25/03/15 18:22:52 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@70809080)) by listener AppStatusListener took 1.11775105s.
[2025-03-15T18:23:16.808+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-03-15T18:23:19.915+0000] {spark_submit.py:488} INFO - 25/03/15 18:23:19 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@1f884698)) by listener AppStatusListener took 1.37352468s.
[2025-03-15T18:23:19.984+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-15T18:23:50.561+0000] {spark_submit.py:488} INFO - 25/03/15 18:23:50 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@795d475a)) by listener AppStatusListener took 20.052766536s.
[2025-03-15T18:24:07.044+0000] {spark_submit.py:488} INFO - 25/03/15 18:24:05 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@24bc726f)) by listener AppStatusListener took 8.785348097s.
[2025-03-15T18:24:13.110+0000] {spark_submit.py:488} INFO - 25/03/15 18:24:11 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@244f8217)) by listener AppStatusListener took 2.757700863s.
[2025-03-15T18:24:26.351+0000] {spark_submit.py:488} INFO - 25/03/15 18:24:25 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@479686db)) by listener AppStatusListener took 1.499196791s.
[2025-03-15T18:24:32.930+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-15T18:24:50.313+0000] {spark_submit.py:488} INFO - 25/03/15 18:24:50 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@54626ee4)) by listener AppStatusListener took 9.794704362s.
[2025-03-15T18:24:55.314+0000] {spark_submit.py:488} INFO - 25/03/15 18:24:55 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@138a410d)) by listener AppStatusListener took 1.548512979s.
[2025-03-15T18:25:00.349+0000] {spark_submit.py:488} INFO - 25/03/15 18:25:00 INFO MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 0 to 172.18.0.6:47064
[2025-03-15T18:25:10.212+0000] {spark_submit.py:488} INFO - 25/03/15 18:25:10 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@2d82a3ec)) by listener AppStatusListener took 1.369231625s.
[2025-03-15T18:25:25.316+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-15T18:25:28.663+0000] {spark_submit.py:488} INFO - 25/03/15 18:25:28 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(0,WrappedArray((2,1,0,Vector(AccumulableInfo(41,Some(internal.metrics.jvmGCTime),Some(1333),None,true,true,None), AccumulableInfo(47,Some(internal.metrics.shuffle.read.remoteBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(48,Some(internal.metrics.shuffle.read.localBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(49,Some(internal.metrics.shuffle.read.remoteBytesRead),Some(0),None,true,true,None), AccumulableInfo(50,Some(internal.metrics.shuffle.read.remoteBytesReadToDisk),Some(0),None,true,true,None), AccumulableInfo(51,Some(internal.metrics.shuffle.read.localBytesRead),Some(0),None,true,true,None), AccumulableInfo(52,Some(internal.metrics.shuffle.read.fetchWaitTime),Some(0),None,true,true,None), AccumulableInfo(53,Some(internal.metrics.shuffle.read.recordsRead),Some(0),None,true,true,None), AccumulableInfo(54,Some(internal.metrics.shuffle.push.read.corruptMergedBlockChunks),Some(0),None,true,true,None), AccumulableInfo(55,Some(internal.metrics.shuffle.push.read.mergedFetchFallbackCount),Some(0),None,true,true,None), AccumulableInfo(56,Some(internal.metrics.shuffle.push.read.remoteMergedBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(57,Some(internal.metrics.shuffle.push.read.localMergedBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(58,Some(internal.metrics.shuffle.push.read.remoteMergedChunksFetched),Some(0),None,true,true,None), AccumulableInfo(59,Some(internal.metrics.shuffle.push.read.localMergedChunksFetched),Some(0),None,true,true,None), AccumulableInfo(60,Some(internal.metrics.shuffle.push.read.remoteMergedBytesRead),Some(0),None,true,true,None), AccumulableInfo(61,Some(internal.metrics.shuffle.push.read.localMergedBytesRead),Some(0),None,true,true,None), AccumulableInfo(62,Some(internal.metrics.shuffle.read.remoteReqsDuration),Some(0),None,true,true,None), AccumulableInfo(63,Some(internal.metrics.shuffle.push.read.remoteMergedReqsDuration),Some(0),None,true,true,None))), (3,1,0,Vector(AccumulableInfo(41,Some(internal.metrics.jvmGCTime),Some(1333),None,true,true,None), AccumulableInfo(47,Some(internal.metrics.shuffle.read.remoteBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(48,Some(internal.metrics.shuffle.read.localBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(49,Some(internal.metrics.shuffle.read.remoteBytesRead),Some(0),None,true,true,None), AccumulableInfo(50,Some(internal.metrics.shuffle.read.remoteBytesReadToDisk),Some(0),None,true,true,None), AccumulableInfo(51,Some(internal.metrics.shuffle.read.localBytesRead),Some(0),None,true,true,None), AccumulableInfo(52,Some(internal.metrics.shuffle.read.fetchWaitTime),Some(0),None,true,true,None), AccumulableInfo(53,Some(internal.metrics.shuffle.read.recordsRead),Some(0),None,true,true,None), AccumulableInfo(54,Some(internal.metrics.shuffle.push.read.corruptMergedBlockChunks),Some(0),None,true,true,None), AccumulableInfo(55,Some(internal.metrics.shuffle.push.read.mergedFetchFallbackCount),Some(0),None,true,true,None), AccumulableInfo(56,Some(internal.metrics.shuffle.push.read.remoteMergedBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(57,Some(internal.metrics.shuffle.push.read.localMergedBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(58,Some(internal.metrics.shuffle.push.read.remoteMergedChunksFetched),Some(0),None,true,true,None), AccumulableInfo(59,Some(internal.metrics.shuffle.push.read.localMergedChunksFetched),Some(0),None,true,true,None), AccumulableInfo(60,Some(internal.metrics.shuffle.push.read.remoteMergedBytesRead),Some(0),None,true,true,None), AccumulableInfo(61,Some(internal.metrics.shuffle.push.read.localMergedBytesRead),Some(0),None,true,true,None), AccumulableInfo(62,Some(internal.metrics.shuffle.read.remoteReqsDuration),Some(0),None,true,true,None), AccumulableInfo(63,Some(internal.metrics.shuffle.push.read.remoteMergedReqsDuration),Some(0),None,true,true,None)))),Map((1,0) -> org.apache.spark.executor.ExecutorMetrics@66d37140)) by listener AppStatusListener took 4.825440143s.
[2025-03-15T18:25:31.987+0000] {spark_submit.py:488} INFO - 25/03/15 18:25:31 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@5f7c3f49)) by listener AppStatusListener took 2.605895442s.
[2025-03-15T18:25:55.681+0000] {spark_submit.py:488} INFO - 25/03/15 18:25:55 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(0,WrappedArray((2,1,0,Vector(AccumulableInfo(41,Some(internal.metrics.jvmGCTime),Some(1333),None,true,true,None), AccumulableInfo(47,Some(internal.metrics.shuffle.read.remoteBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(48,Some(internal.metrics.shuffle.read.localBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(49,Some(internal.metrics.shuffle.read.remoteBytesRead),Some(0),None,true,true,None), AccumulableInfo(50,Some(internal.metrics.shuffle.read.remoteBytesReadToDisk),Some(0),None,true,true,None), AccumulableInfo(51,Some(internal.metrics.shuffle.read.localBytesRead),Some(0),None,true,true,None), AccumulableInfo(52,Some(internal.metrics.shuffle.read.fetchWaitTime),Some(0),None,true,true,None), AccumulableInfo(53,Some(internal.metrics.shuffle.read.recordsRead),Some(0),None,true,true,None), AccumulableInfo(54,Some(internal.metrics.shuffle.push.read.corruptMergedBlockChunks),Some(0),None,true,true,None), AccumulableInfo(55,Some(internal.metrics.shuffle.push.read.mergedFetchFallbackCount),Some(0),None,true,true,None), AccumulableInfo(56,Some(internal.metrics.shuffle.push.read.remoteMergedBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(57,Some(internal.metrics.shuffle.push.read.localMergedBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(58,Some(internal.metrics.shuffle.push.read.remoteMergedChunksFetched),Some(0),None,true,true,None), AccumulableInfo(59,Some(internal.metrics.shuffle.push.read.localMergedChunksFetched),Some(0),None,true,true,None), AccumulableInfo(60,Some(internal.metrics.shuffle.push.read.remoteMergedBytesRead),Some(0),None,true,true,None), AccumulableInfo(61,Some(internal.metrics.shuffle.push.read.localMergedBytesRead),Some(0),None,true,true,None), AccumulableInfo(62,Some(internal.metrics.shuffle.read.remoteReqsDuration),Some(0),None,true,true,None), AccumulableInfo(63,Some(internal.metrics.shuffle.push.read.remoteMergedReqsDuration),Some(0),None,true,true,None))), (3,1,0,Vector(AccumulableInfo(41,Some(internal.metrics.jvmGCTime),Some(1333),None,true,true,None), AccumulableInfo(47,Some(internal.metrics.shuffle.read.remoteBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(48,Some(internal.metrics.shuffle.read.localBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(49,Some(internal.metrics.shuffle.read.remoteBytesRead),Some(0),None,true,true,None), AccumulableInfo(50,Some(internal.metrics.shuffle.read.remoteBytesReadToDisk),Some(0),None,true,true,None), AccumulableInfo(51,Some(internal.metrics.shuffle.read.localBytesRead),Some(0),None,true,true,None), AccumulableInfo(52,Some(internal.metrics.shuffle.read.fetchWaitTime),Some(0),None,true,true,None), AccumulableInfo(53,Some(internal.metrics.shuffle.read.recordsRead),Some(0),None,true,true,None), AccumulableInfo(54,Some(internal.metrics.shuffle.push.read.corruptMergedBlockChunks),Some(0),None,true,true,None), AccumulableInfo(55,Some(internal.metrics.shuffle.push.read.mergedFetchFallbackCount),Some(0),None,true,true,None), AccumulableInfo(56,Some(internal.metrics.shuffle.push.read.remoteMergedBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(57,Some(internal.metrics.shuffle.push.read.localMergedBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(58,Some(internal.metrics.shuffle.push.read.remoteMergedChunksFetched),Some(0),None,true,true,None), AccumulableInfo(59,Some(internal.metrics.shuffle.push.read.localMergedChunksFetched),Some(0),None,true,true,None), AccumulableInfo(60,Some(internal.metrics.shuffle.push.read.remoteMergedBytesRead),Some(0),None,true,true,None), AccumulableInfo(61,Some(internal.metrics.shuffle.push.read.localMergedBytesRead),Some(0),None,true,true,None), AccumulableInfo(62,Some(internal.metrics.shuffle.read.remoteReqsDuration),Some(0),None,true,true,None), AccumulableInfo(63,Some(internal.metrics.shuffle.push.read.remoteMergedReqsDuration),Some(0),None,true,true,None)))),Map((1,0) -> org.apache.spark.executor.ExecutorMetrics@6aa65400)) by listener AppStatusListener took 8.687435854s.
[2025-03-15T18:25:59.298+0000] {spark_submit.py:488} INFO - 25/03/15 18:25:58 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@5283077b)) by listener AppStatusListener took 2.989455196s.
[2025-03-15T18:26:06.738+0000] {spark_submit.py:488} INFO - 25/03/15 18:26:05 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@2f27351a)) by listener AppStatusListener took 4.860937936s.
[2025-03-15T18:26:09.782+0000] {spark_submit.py:488} INFO - 25/03/15 18:26:08 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(0,WrappedArray((2,1,0,Vector(AccumulableInfo(41,Some(internal.metrics.jvmGCTime),Some(1333),None,true,true,None), AccumulableInfo(47,Some(internal.metrics.shuffle.read.remoteBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(48,Some(internal.metrics.shuffle.read.localBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(49,Some(internal.metrics.shuffle.read.remoteBytesRead),Some(0),None,true,true,None), AccumulableInfo(50,Some(internal.metrics.shuffle.read.remoteBytesReadToDisk),Some(0),None,true,true,None), AccumulableInfo(51,Some(internal.metrics.shuffle.read.localBytesRead),Some(0),None,true,true,None), AccumulableInfo(52,Some(internal.metrics.shuffle.read.fetchWaitTime),Some(0),None,true,true,None), AccumulableInfo(53,Some(internal.metrics.shuffle.read.recordsRead),Some(0),None,true,true,None), AccumulableInfo(54,Some(internal.metrics.shuffle.push.read.corruptMergedBlockChunks),Some(0),None,true,true,None), AccumulableInfo(55,Some(internal.metrics.shuffle.push.read.mergedFetchFallbackCount),Some(0),None,true,true,None), AccumulableInfo(56,Some(internal.metrics.shuffle.push.read.remoteMergedBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(57,Some(internal.metrics.shuffle.push.read.localMergedBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(58,Some(internal.metrics.shuffle.push.read.remoteMergedChunksFetched),Some(0),None,true,true,None), AccumulableInfo(59,Some(internal.metrics.shuffle.push.read.localMergedChunksFetched),Some(0),None,true,true,None), AccumulableInfo(60,Some(internal.metrics.shuffle.push.read.remoteMergedBytesRead),Some(0),None,true,true,None), AccumulableInfo(61,Some(internal.metrics.shuffle.push.read.localMergedBytesRead),Some(0),None,true,true,None), AccumulableInfo(62,Some(internal.metrics.shuffle.read.remoteReqsDuration),Some(0),None,true,true,None), AccumulableInfo(63,Some(internal.metrics.shuffle.push.read.remoteMergedReqsDuration),Some(0),None,true,true,None))), (3,1,0,Vector(AccumulableInfo(41,Some(internal.metrics.jvmGCTime),Some(1333),None,true,true,None), AccumulableInfo(47,Some(internal.metrics.shuffle.read.remoteBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(48,Some(internal.metrics.shuffle.read.localBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(49,Some(internal.metrics.shuffle.read.remoteBytesRead),Some(0),None,true,true,None), AccumulableInfo(50,Some(internal.metrics.shuffle.read.remoteBytesReadToDisk),Some(0),None,true,true,None), AccumulableInfo(51,Some(internal.metrics.shuffle.read.localBytesRead),Some(0),None,true,true,None), AccumulableInfo(52,Some(internal.metrics.shuffle.read.fetchWaitTime),Some(0),None,true,true,None), AccumulableInfo(53,Some(internal.metrics.shuffle.read.recordsRead),Some(0),None,true,true,None), AccumulableInfo(54,Some(internal.metrics.shuffle.push.read.corruptMergedBlockChunks),Some(0),None,true,true,None), AccumulableInfo(55,Some(internal.metrics.shuffle.push.read.mergedFetchFallbackCount),Some(0),None,true,true,None), AccumulableInfo(56,Some(internal.metrics.shuffle.push.read.remoteMergedBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(57,Some(internal.metrics.shuffle.push.read.localMergedBlocksFetched),Some(0),None,true,true,None), AccumulableInfo(58,Some(internal.metrics.shuffle.push.read.remoteMergedChunksFetched),Some(0),None,true,true,None), AccumulableInfo(59,Some(internal.metrics.shuffle.push.read.localMergedChunksFetched),Some(0),None,true,true,None), AccumulableInfo(60,Some(internal.metrics.shuffle.push.read.remoteMergedBytesRead),Some(0),None,true,true,None), AccumulableInfo(61,Some(internal.metrics.shuffle.push.read.localMergedBytesRead),Some(0),None,true,true,None), AccumulableInfo(62,Some(internal.metrics.shuffle.read.remoteReqsDuration),Some(0),None,true,true,None), AccumulableInfo(63,Some(internal.metrics.shuffle.push.read.remoteMergedReqsDuration),Some(0),None,true,true,None)))),Map((1,0) -> org.apache.spark.executor.ExecutorMetrics@111fc1c0)) by listener AppStatusListener took 1.37489454s.
[2025-03-15T18:26:14.353+0000] {spark_submit.py:488} INFO - 25/03/15 18:26:13 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@494181b7)) by listener AppStatusListener took 3.000456183s.
[2025-03-15T18:26:14.353+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-15T18:26:16.864+0000] {spark_submit.py:488} INFO - 25/03/15 18:26:15 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@333ff3b)) by listener AppStatusListener took 1.826651597s.
[2025-03-15T18:26:42.270+0000] {spark_submit.py:488} INFO - 25/03/15 18:26:41 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@15aa95a2)) by listener AppStatusListener took 1.393896889s.
[2025-03-15T18:27:01.868+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-15T18:27:05.798+0000] {spark_submit.py:488} INFO - 25/03/15 18:27:05 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@7ad44716)) by listener AppStatusListener took 1.800923841s.
[2025-03-15T18:27:42.074+0000] {spark_submit.py:488} INFO - 25/03/15 18:27:40 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@3f5d3dc2)) by listener AppStatusListener took 1.791102451s.
[2025-03-15T18:27:46.192+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-15T18:27:50.408+0000] {local_task_job_runner.py:228} ERROR - Heartbeat time limit exceeded!
[2025-03-15T18:27:51.049+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-15T18:27:57.243+0000] {spark_submit.py:488} INFO - 25/03/15 18:27:56 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@230bc735)) by listener AppStatusListener took 2.500767398s.
[2025-03-15T18:27:59.842+0000] {process_utils.py:132} INFO - Sending 15 to group 102. PIDs of all processes in the group: [104, 143, 102]
[2025-03-15T18:28:03.316+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 102
[2025-03-15T18:28:12.479+0000] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-15T18:28:12.768+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=143, status='terminated', started='18:20:11') (143) terminated with exit code None
[2025-03-15T18:28:13.558+0000] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
  File "/home/***/.local/lib/python3.12/site-packages/***/__main__.py", line 62, in main
    args.func(args)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 64, in wrapper
    providers_configuration_loaded(func)(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 237, in worker
    _run_command_with_daemon_option(
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 50, in _run_command_with_daemon_option
    run_command_with_daemon_option(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 230, in run_celery_worker
    celery_app.worker_main(options)
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
  File "/home/***/.local/lib/python3.12/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
  File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
  File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
  File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 651, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 139, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 171, in _execute_in_fork
    args.func(args)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/apache/spark/hooks/spark_submit.py", line 407, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/apache/spark/hooks/spark_submit.py", line 488, in _process_spark_submit_log
    self.log.info(line)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1539, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1682, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args,
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1651, in makeRecord
    rv = _logRecordFactory(name, level, fn, lno, msg, args, exc_info, func,
  File "/usr/local/lib/python3.12/logging/__init__.py", line 372, in __init__
    asyncio = sys.modules.get('asyncio')
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-03-15T18:28:13.609+0000] {spark_submit.py:623} INFO - Sending kill signal to spark-submit
[2025-03-15T18:28:16.523+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 407, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 488, in _process_spark_submit_log
    self.log.info(line)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1539, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1682, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1651, in makeRecord
    rv = _logRecordFactory(name, level, fn, lno, msg, args, exc_info, func,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/__init__.py", line 372, in __init__
    asyncio = sys.modules.get('asyncio')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-03-15T18:28:16.855+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=solar_energy_crops_pipeline, task_id=first_task, run_id=manual__2025-03-15T18:20:02.677832+00:00, execution_date=20250315T182002, start_date=20250315T182007, end_date=20250315T182816
[2025-03-15T18:28:17.297+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-15T18:28:17.391+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=104, status='terminated', started='18:20:07') (104) terminated with exit code None
[2025-03-15T18:28:17.393+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=102, status='terminated', exitcode=2, started='18:20:07') (102) terminated with exit code 2
