[2025-03-15T08:01:56.823+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-15T08:01:56.847+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.first_task manual__2025-03-15T08:01:52.751341+00:00 [queued]>
[2025-03-15T08:01:56.858+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.first_task manual__2025-03-15T08:01:52.751341+00:00 [queued]>
[2025-03-15T08:01:56.859+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-15T08:01:56.877+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): first_task> on 2025-03-15 08:01:52.751341+00:00
[2025-03-15T08:01:56.887+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=100) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-15T08:01:56.889+0000] {standard_task_runner.py:72} INFO - Started process 101 to run task
[2025-03-15T08:01:56.889+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'solar_energy_crops_pipeline', 'first_task', 'manual__2025-03-15T08:01:52.751341+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/mainDag.py', '--cfg-path', '/tmp/tmph8w91x7n']
[2025-03-15T08:01:56.890+0000] {standard_task_runner.py:105} INFO - Job 82: Subtask first_task
[2025-03-15T08:01:56.949+0000] {task_command.py:467} INFO - Running <TaskInstance: solar_energy_crops_pipeline.first_task manual__2025-03-15T08:01:52.751341+00:00 [running]> on host 1a91693e05ec
[2025-03-15T08:01:57.039+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_energy_crops_pipeline' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T08:01:52.751341+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-15T08:01:52.751341+00:00'
[2025-03-15T08:01:57.040+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-15T08:01:57.068+0000] {base.py:84} INFO - Retrieving connection 'spark_mm'
[2025-03-15T08:01:57.070+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/Script1.py
[2025-03-15T08:02:04.376+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO SparkContext: Running Spark version 3.5.5
[2025-03-15T08:02:04.378+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-03-15T08:02:04.379+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO SparkContext: Java version 17.0.14
[2025-03-15T08:02:04.488+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-15T08:02:04.758+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO ResourceUtils: ==============================================================
[2025-03-15T08:02:04.758+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-15T08:02:04.759+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO ResourceUtils: ==============================================================
[2025-03-15T08:02:04.760+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO SparkContext: Submitted application: PythonWordCount
[2025-03-15T08:02:04.847+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-15T08:02:04.853+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO ResourceProfile: Limiting resource is cpu
[2025-03-15T08:02:04.855+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-15T08:02:04.991+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO SecurityManager: Changing view acls to: ***
[2025-03-15T08:02:04.992+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO SecurityManager: Changing modify acls to: ***
[2025-03-15T08:02:04.993+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO SecurityManager: Changing view acls groups to:
[2025-03-15T08:02:04.993+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO SecurityManager: Changing modify acls groups to:
[2025-03-15T08:02:04.994+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:04 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-03-15T08:02:05.576+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:05 INFO Utils: Successfully started service 'sparkDriver' on port 36557.
[2025-03-15T08:02:05.683+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:05 INFO SparkEnv: Registering MapOutputTracker
[2025-03-15T08:02:05.769+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:05 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-15T08:02:05.855+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:05 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-15T08:02:05.856+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:05 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-15T08:02:05.862+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:05 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-15T08:02:05.903+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:05 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-73486190-5017-469d-b34c-e8c92e1f5534
[2025-03-15T08:02:05.946+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:05 INFO MemoryStore: MemoryStore started with capacity 413.9 MiB
[2025-03-15T08:02:05.961+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:05 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-15T08:02:06.259+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:06 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-15T08:02:06.369+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:06 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-15T08:02:07.064+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:07 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-03-15T08:02:07.568+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:07 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.5:7077 after 210 ms (0 ms spent in bootstraps)
[2025-03-15T08:02:08.130+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:08 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250315080208-0000
[2025-03-15T08:02:08.140+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:08 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45297.
[2025-03-15T08:02:08.141+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:08 INFO NettyBlockTransferService: Server created on 1a91693e05ec:45297
[2025-03-15T08:02:08.144+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:08 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-15T08:02:08.152+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:08 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 1a91693e05ec, 45297, None)
[2025-03-15T08:02:08.156+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:08 INFO BlockManagerMasterEndpoint: Registering block manager 1a91693e05ec:45297 with 413.9 MiB RAM, BlockManagerId(driver, 1a91693e05ec, 45297, None)
[2025-03-15T08:02:08.158+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:08 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 1a91693e05ec, 45297, None)
[2025-03-15T08:02:08.160+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:08 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 1a91693e05ec, 45297, None)
[2025-03-15T08:02:08.217+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:08 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250315080208-0000/0 on worker-20250315075842-172.18.0.6-43055 (172.18.0.6:43055) with 2 core(s)
[2025-03-15T08:02:08.230+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:08 INFO StandaloneSchedulerBackend: Granted executor ID app-20250315080208-0000/0 on hostPort 172.18.0.6:43055 with 2 core(s), 1024.0 MiB RAM
[2025-03-15T08:02:08.711+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:08 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-15T08:02:09.754+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:09 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250315080208-0000/0 is now RUNNING
[2025-03-15T08:02:09.861+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:09 INFO SparkContext: Starting job: collect at /opt/***/dags/Script1.py:21
[2025-03-15T08:02:09.965+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:09 INFO DAGScheduler: Registering RDD 2 (reduceByKey at /opt/***/dags/Script1.py:19) as input to shuffle 0
[2025-03-15T08:02:09.970+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:09 INFO DAGScheduler: Got job 0 (collect at /opt/***/dags/Script1.py:21) with 2 output partitions
[2025-03-15T08:02:09.971+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:09 INFO DAGScheduler: Final stage: ResultStage 1 (collect at /opt/***/dags/Script1.py:21)
[2025-03-15T08:02:09.972+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:09 INFO DAGScheduler: Parents of final stage: List(ShuffleMapStage 0)
[2025-03-15T08:02:09.973+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:09 INFO DAGScheduler: Missing parents: List(ShuffleMapStage 0)
[2025-03-15T08:02:09.976+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:09 INFO DAGScheduler: Submitting ShuffleMapStage 0 (PairwiseRDD[2] at reduceByKey at /opt/***/dags/Script1.py:19), which has no missing parents
[2025-03-15T08:02:10.255+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:10 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 10.9 KiB, free 413.9 MiB)
[2025-03-15T08:02:10.362+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:10 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 7.0 KiB, free 413.9 MiB)
[2025-03-15T08:02:10.368+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:10 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 1a91693e05ec:45297 (size: 7.0 KiB, free: 413.9 MiB)
[2025-03-15T08:02:10.436+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:10 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1585
[2025-03-15T08:02:10.461+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:10 INFO DAGScheduler: Submitting 2 missing tasks from ShuffleMapStage 0 (PairwiseRDD[2] at reduceByKey at /opt/***/dags/Script1.py:19) (first 15 tasks are for partitions Vector(0, 1))
[2025-03-15T08:02:10.464+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:10 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks resource profile 0
[2025-03-15T08:02:13.040+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:13 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.6:54778) with ID 0,  ResourceProfileId 0
[2025-03-15T08:02:13.141+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:13 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.6:46255 with 434.4 MiB RAM, BlockManagerId(0, 172.18.0.6, 46255, None)
[2025-03-15T08:02:13.223+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:13 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.18.0.6, executor 0, partition 0, PROCESS_LOCAL, 9212 bytes)
[2025-03-15T08:02:13.226+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:13 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1) (172.18.0.6, executor 0, partition 1, PROCESS_LOCAL, 9219 bytes)
[2025-03-15T08:02:13.611+0000] {spark_submit.py:488} INFO - 25/03/15 08:02:13 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.18.0.6:46255 (size: 7.0 KiB, free: 434.4 MiB)
[2025-03-15T08:04:08.533+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-03-15T10:39:37.426+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-15T10:39:38.119+0000] {local_task_job_runner.py:228} ERROR - Heartbeat time limit exceeded!
[2025-03-15T10:39:38.597+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-15T10:39:41.406+0000] {process_utils.py:132} INFO - Sending 15 to group 101. PIDs of all processes in the group: [103, 142, 101]
[2025-03-15T10:39:41.477+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 101
[2025-03-15T10:39:42.068+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=142, status='terminated', started='08:02:01') (142) terminated with exit code None
[2025-03-15T10:39:41.853+0000] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-15T10:39:42.765+0000] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
  File "/home/***/.local/lib/python3.12/site-packages/***/__main__.py", line 62, in main
    args.func(args)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 64, in wrapper
    providers_configuration_loaded(func)(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 237, in worker
    _run_command_with_daemon_option(
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 50, in _run_command_with_daemon_option
    run_command_with_daemon_option(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 230, in run_celery_worker
    celery_app.worker_main(options)
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
  File "/home/***/.local/lib/python3.12/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
  File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
  File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
  File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 651, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 139, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 171, in _execute_in_fork
    args.func(args)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/apache/spark/hooks/spark_submit.py", line 407, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/apache/spark/hooks/spark_submit.py", line 456, in _process_spark_submit_log
    for line in itr:
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-03-15T10:39:42.853+0000] {spark_submit.py:623} INFO - Sending kill signal to spark-submit
