[2025-03-03T05:44:39.677+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T05:44:39.729+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.extract_data scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-03T05:44:39.750+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.extract_data scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-03T05:44:39.752+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-03T05:44:39.789+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-03-02 00:00:00+00:00
[2025-03-03T05:44:39.811+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-03T05:44:39.816+0000] {standard_task_runner.py:72} INFO - Started process 70 to run task
[2025-03-03T05:44:39.816+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'solar_energy_crops_pipeline', 'extract_data', 'scheduled__2025-03-02T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/mainDag.py', '--cfg-path', '/tmp/tmpzq1qull4']
[2025-03-03T05:44:39.831+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask extract_data
[2025-03-03T05:44:40.039+0000] {task_command.py:467} INFO - Running <TaskInstance: solar_energy_crops_pipeline.extract_data scheduled__2025-03-02T00:00:00+00:00 [running]> on host eb4bbf78a3cf
[2025-03-03T05:44:40.334+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_energy_crops_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T00:00:00+00:00'
[2025-03-03T05:44:40.337+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-03T05:44:40.434+0000] {logging_mixin.py:190} INFO - Extracting data from API...
[2025-03-03T05:44:40.441+0000] {logging_mixin.py:190} INFO - Fetching data for year 2013
[2025-03-03T05:44:43.046+0000] {logging_mixin.py:190} INFO - Sleeping for a while to respect API rate limits...
[2025-03-03T05:44:51.050+0000] {logging_mixin.py:190} INFO - Fetching data for year 2014
[2025-03-03T05:44:52.149+0000] {logging_mixin.py:190} INFO - Sleeping for a while to respect API rate limits...
[2025-03-03T05:45:00.139+0000] {logging_mixin.py:190} INFO - Fetching data for year 2015
[2025-03-03T05:45:01.225+0000] {logging_mixin.py:190} INFO - Sleeping for a while to respect API rate limits...
[2025-03-03T05:45:09.234+0000] {logging_mixin.py:190} INFO - Fetching data for year 2016
[2025-03-03T05:45:12.204+0000] {logging_mixin.py:190} INFO - Sleeping for a while to respect API rate limits...
[2025-03-03T05:45:20.212+0000] {logging_mixin.py:190} INFO - Fetching data for year 2017
[2025-03-03T05:45:22.307+0000] {logging_mixin.py:190} INFO - Sleeping for a while to respect API rate limits...
[2025-03-03T05:45:30.321+0000] {logging_mixin.py:190} INFO - Done fetching all years!
[2025-03-03T05:45:30.323+0000] {logging_mixin.py:190} INFO - Extraction completed
[2025-03-03T05:45:31.128+0000] {logging_mixin.py:190} INFO - Error saving data to GCS: ('invalid_grant: Invalid grant: account not found', {'error': 'invalid_grant', 'error_description': 'Invalid grant: account not found'})
[2025-03-03T05:45:31.297+0000] {logging_mixin.py:190} INFO - Error saving data to GCS: ('invalid_grant: Invalid grant: account not found', {'error': 'invalid_grant', 'error_description': 'Invalid grant: account not found'})
[2025-03-03T05:45:31.532+0000] {logging_mixin.py:190} INFO - Error saving data to GCS: ('invalid_grant: Invalid grant: account not found', {'error': 'invalid_grant', 'error_description': 'Invalid grant: account not found'})
[2025-03-03T05:45:31.705+0000] {logging_mixin.py:190} INFO - Error saving data to GCS: ('invalid_grant: Invalid grant: account not found', {'error': 'invalid_grant', 'error_description': 'Invalid grant: account not found'})
[2025-03-03T05:45:31.909+0000] {logging_mixin.py:190} INFO - Error saving data to GCS: ('invalid_grant: Invalid grant: account not found', {'error': 'invalid_grant', 'error_description': 'Invalid grant: account not found'})
[2025-03-03T05:45:32.021+0000] {logging_mixin.py:190} INFO - Error saving data to GCS: ('invalid_grant: Invalid grant: account not found', {'error': 'invalid_grant', 'error_description': 'Invalid grant: account not found'})
[2025-03-03T05:45:32.219+0000] {logging_mixin.py:190} INFO - Error saving data to GCS: ('invalid_grant: Invalid grant: account not found', {'error': 'invalid_grant', 'error_description': 'Invalid grant: account not found'})
[2025-03-03T05:45:32.423+0000] {logging_mixin.py:190} INFO - Error saving data to GCS: ('invalid_grant: Invalid grant: account not found', {'error': 'invalid_grant', 'error_description': 'Invalid grant: account not found'})
[2025-03-03T05:45:32.626+0000] {logging_mixin.py:190} INFO - Error saving data to GCS: ('invalid_grant: Invalid grant: account not found', {'error': 'invalid_grant', 'error_description': 'Invalid grant: account not found'})
[2025-03-03T05:45:32.739+0000] {logging_mixin.py:190} INFO - Error saving data to GCS: ('invalid_grant: Invalid grant: account not found', {'error': 'invalid_grant', 'error_description': 'Invalid grant: account not found'})
[2025-03-03T05:45:41.309+0000] {logging_mixin.py:190} INFO - Data saved to PostgreSQL table: solar_crops_raw
[2025-03-03T05:45:41.409+0000] {logging_mixin.py:190} INFO - Data saved to PostgreSQL table: solar_crops_raw
[2025-03-03T05:45:41.434+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T05:45:41.453+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-03T05:45:41.454+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=solar_energy_crops_pipeline, task_id=extract_data, run_id=scheduled__2025-03-02T00:00:00+00:00, execution_date=20250302T000000, start_date=20250303T054439, end_date=20250303T054541
[2025-03-03T05:45:41.526+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T05:45:41.544+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-03T05:45:41.549+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
