[2025-03-02T19:32:00.340+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T19:32:00.360+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.extract_data manual__2025-03-02T18:59:03.734635+00:00 [queued]>
[2025-03-02T19:32:00.369+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.extract_data manual__2025-03-02T18:59:03.734635+00:00 [queued]>
[2025-03-02T19:32:00.372+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-03-02T19:32:00.387+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-03-02 18:59:03.734635+00:00
[2025-03-02T19:32:00.401+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=915) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-02T19:32:00.403+0000] {standard_task_runner.py:72} INFO - Started process 917 to run task
[2025-03-02T19:32:00.402+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'solar_energy_crops_pipeline', 'extract_data', 'manual__2025-03-02T18:59:03.734635+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/mainDag.py', '--cfg-path', '/tmp/tmplal9dxpw']
[2025-03-02T19:32:00.408+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask extract_data
[2025-03-02T19:32:00.469+0000] {task_command.py:467} INFO - Running <TaskInstance: solar_energy_crops_pipeline.extract_data manual__2025-03-02T18:59:03.734635+00:00 [running]> on host 7465e3cb0781
[2025-03-02T19:32:00.572+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_energy_crops_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T18:59:03.734635+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T18:59:03.734635+00:00'
[2025-03-02T19:32:00.574+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-02T19:32:00.604+0000] {logging_mixin.py:190} INFO - Extracting data from API...
[2025-03-02T19:32:00.609+0000] {logging_mixin.py:190} INFO - Fetching data for year 1967
[2025-03-02T19:32:02.302+0000] {logging_mixin.py:190} INFO - Sleeping for a while to respect API rate limits...
[2025-03-02T19:32:32.310+0000] {logging_mixin.py:190} INFO - Fetching data for year 1968
[2025-03-02T19:32:33.858+0000] {logging_mixin.py:190} INFO - Sleeping for a while to respect API rate limits...
[2025-03-02T19:32:55.889+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-03-02T19:32:55.894+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-02T19:32:55.901+0000] {process_utils.py:132} INFO - Sending 15 to group 917. PIDs of all processes in the group: [917]
[2025-03-02T19:32:55.902+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 917
[2025-03-02T19:32:55.904+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-02T19:32:55.946+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-02T19:32:55.957+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=917, status='terminated', exitcode=0, started='19:31:59') (917) terminated with exit code 0
